name: YouTube Plus + YouPiP, YTUHD and RYD

on:
  workflow_dispatch:
    inputs:
      ipa_url:
        description: "The direct URL to the decrypted IPA file"
        default: ""
        required: true
        type: string

      tweak_version:
        description: "The version of the tweak to use. Enter the version manually from dayanch96/YTLite/releases or leave default"
        default: "5.0.2"
        required: true
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: 
    runs-on: macos-12
    permissions:
      contents: write

    steps:
      - name: Checkout Main
        uses: actions/checkout@v4.1.1
        with:
          path: main
          submodules: recursive

      - name: Install Cyan
        run: |
          pipx install --force https://github.com/asdfzxcvbn/pyzule-rw/archive/main.zip
          pipx inject cyan lief
          pipx inject cyan Pillow

      - name: Download YouTube
        id: download_youtube
        run: wget "${{ inputs.ipa_url }}" --no-verbose -O ${{ github.workspace }}/youtube.ipa

      - name: Download YouTube Plus
        id: download_ytp
        run: |
          deb_url="https://github.com/dayanch96/YTLite/releases/download/v${{ inputs.tweak_version }}/com.dvntm.ytlite_${{ inputs.tweak_version }}_iphoneos-arm.deb"
          wget "$deb_url" --no-verbose -O ${{ github.workspace }}/ytplus.deb

      - name: Clone Open in YouTube (Safari extension)
        run: |
          git clone --quiet -n --depth=1 --filter=tree:0 https://github.com/CokePokes/YoutubeExtensions/
          cd YoutubeExtensions
          git sparse-checkout set --no-cone OpenYoutubeSafariExtension.appex
          git checkout
          mv *.appex ${{ github.workspace }}

      - name: Clone YouPiP
        run: |
          deb_url="https://poomsmart.github.io/repo/debs/youtube/youpip/com.ps.youpip_1.8.14_iphoneos-arm.deb"
          wget "$deb_url" --no-verbose -O ${{ github.workspace }}/youpip.deb

      - name: Clone YTUHD
        run: |
          deb_url="https://poomsmart.github.io/repo/debs/youtube/ytuhd/com.ps.ytuhd_1.5.5_iphoneos-arm.deb"
          wget "$deb_url" --no-verbose -O ${{ github.workspace }}/ytuhd.deb
      - name: Clone Return-YouTube-Dislikes
        run: |
          deb_url="https://repo.chariz.com/debs/Fse5H68N3u07vfZ1wuA9AnU0TWxODBLmpKV8vZqXwJyZyxcLCX_QvhYZnNgMdmZhltgxBqABjm5Ouhv2lCm7xA/weeb.lillie.youtubedislikesreturn_1.12.7_iphoneos-arm.deb"
          wget "$deb_url" --no-verbose -O ${{ github.workspace }}/ryd.deb

      - name: Inject tweaks into IPA
        run: cyan -i ${{ github.workspace }}/youtube.ipa -o ${{ github.workspace }}/YouTubePlus_${{ inputs.tweak_version }}_Tweaks.ipa -u -w -s -g -q -m 14.0 -f ${{ github.workspace }}/ytplus.deb ${{ github.workspace }}/OpenYoutubeSafariExtension.appex ${{ github.workspace }}/youpip.deb ${{ github.workspace }}/ytuhd.deb ${{ github.workspace }}/ryd.deb

      - name: Upload to GitHub Releases
        uses: softprops/action-gh-release@v2.0.1
        with:
          tag_name: v${{ github.run_number }}
          name: YouTubePlus v${{ inputs.tweak_version }} + Tweaks (${{ github.run_number }})
          files: YouTubePlus_${{ inputs.tweak_version }}_Tweaks.ipa
          draft: true
